version: '2'
services:
    podiumuaa-app:
        image: podiumuaa
        external_links:
            - podiumuaa-postgresql:postgresql
            - podiumuaa-elasticsearch:elasticsearch
            - podium-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/podiumUaa
            - PODIUM_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
    podiumuaa-postgresql:
        extends:
            file: postgresql.yml
            service: podiumuaa-postgresql
    podiumuaa-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: podiumuaa-elasticsearch
    podium-registry:
        extends:
            file: podium-registry.yml
            service: podium-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
