version: '2'
services:
    podiumuaa-postgresql:
        container_name: podiumuaa-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/podium/podiumUaa/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=podiumUaa
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
