os:
  - linux
services:
  - docker
language: java
node_js:
  - "7"
jdk:
  - oraclejdk8
sudo: true
cache:
  yarn: true
  directories:
    - node
    - node_modules
    - $HOME/.m2
env:
  global:
    - NODE_VERSION=7.5.0
    - PROFILE=dev
    - RUN_PODIUM=1
    - PROTRACTOR=1
    - PODIUM_BASE=$TRAVIS_BUILD_DIR
    - PODIUM_TRAVIS=$TRAVIS_BUILD_DIR/travis
    - PODIUM_SCRIPTS=$PODIUM_TRAVIS/scripts
    # environment properties
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - MAVEN_OPTS="-Dorg.slf4j.simpleLogger.log.org.apache.maven.cl‌​i.transfer.Slf4jMave‌​nTransferListener=wa‌​rn"
    - PODIUM_UAA_RUN_PORT=8999
addons:
  browserstack:
    username: "thehyve1"
    access_key:
        secure: "LTjZPzCC0VpavmmSmN9KuDf9mzqiECpl4Zf9Jsx5wKgMyG4azcLUMwvpXHm8LTZpuXYyMvaxNJp8aZrtfI3xJ+VWAB63PabIl2J8bMv2BSNSAveWyp6DqSKPegtlhWg31lggAf+kjRJ2f5c5yI7S1VsHUdyUbKPuhG2h56unVKZTbxiQxnYUpri2JZcKD19BmX6xxRddJsJhp8OE7UWgRjBHZFVhZB+CgkKT7WgxzTTvQuA7VlsHW3nAT8In9ehaReFUFWAhPrxmfgav9A63mQWOX3e1+Af4xa/+eG45u0N1/6ENcx1TnOI44/6RRwqULvcQd99pItsnAgw8TnYzX6+KD5XDJMXpeV9nVkF9slaiPiR+y5HJjdgeJ1QdMAhPGbeNruVdDSb4Qi8MhpBjQSdZpF8WQlUo+r/DaWF8C4POtWk20wI3UaPXJOKc/05cXHU+tinSM9hlizXWgJviLOQiQrg/EKtCAe2wz/bc2zlfR1OPq5lX5nLM09RkPgTFALXv8auxJwaC/2kFoG8liNPDL5RGcsO21GTVrpJ4XEzwH0hSlgHNwEzxP5i7n9I51z0AucKZg8BJFSV2I/UnoLSCx88kzISNQBgNk6hhSlKvoh8zrNN87Vy8LJoXj7VNGYymoDGlWT6Aa+9XRKljRavHHVUkxZZWd16mE4/uqg0="
before_install:
  - nvm install $NODE_VERSION
  - node -v
  - yarn --version
  - java -version
  - export TZ=Europe/Amsterdam
  - date
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - chmod +x $PODIUM_SCRIPTS/*
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - mvn install -DskipTests -q
  - pushd podium-gateway
  - yarn install
  - yarn link
  - popd
script:
  - $PODIUM_SCRIPTS/01-docker-compose.sh
  #- $PODIUM_SCRIPTS/02-tests.sh
  - $PODIUM_SCRIPTS/03-run.sh
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
