os:
  - linux
services:
  - docker
language: java
node_js:
  - "7.5.0"
jdk:
  - oraclejdk8
sudo: false
cache:
  yarn: true
  directories:
    - node
    - node_modules
    - $HOME/.m2
    - $HOME/.yarn-cache
env:
  global:
    - NODE_VERSION=7.5.0
    - PROFILE=dev
    - RUN_PODIUM=1
    - PROTRACTOR=0
    - PODIUM_BASE=$TRAVIS_BUILD_DIR
    - PODIUM_TRAVIS=$TRAVIS_BUILD_DIR/travis
    - PODIUM_SCRIPTS=$PODIUM_TRAVIS/scripts
    # environment properties
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - MAVEN_OPTS="-Dorg.slf4j.simpleLogger.log.org.apache.maven.cl‌​i.transfer.Slf4jMave‌​nTransferListener=wa‌​rn"
before_install:
  - nvm install $NODE_VERSION
  - npm install -g npm
  # Install Yarn from repo
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - export PATH=$HOME/.yarn/bin:$PATH
  - node -v
  - npm -v
  - yarn -v
  - java -version
  - export TZ=Europe/Amsterdam
  - date
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - chmod +x $PODIUM_SCRIPTS/*
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - pushd podium-gateway && yarn install && popd
  - pushd podium-common && mvn install && popd
script:
  - $PODIUM_SCRIPTS/01-docker-compose.sh
  - $PODIUM_SCRIPTS/02-tests.sh
  - $PODIUM_SCRIPTS/03-run.sh
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
