os:
  - linux
services:
  - docker
language: java
node_js:
  - "7"
jdk:
  - oraclejdk8
sudo: true
cache:
  yarn: true
  directories:
    - node
    - node_modules
    - $HOME/.m2
env:
  global:
    - NODE_VERSION=7.5.0
    - PROFILE=dev
    - RUN_PODIUM=1
    - PROTRACTOR=1
    - PODIUM_BASE=$TRAVIS_BUILD_DIR
    - PODIUM_TRAVIS=$TRAVIS_BUILD_DIR/travis
    - PODIUM_SCRIPTS=$PODIUM_TRAVIS/scripts
    # environment properties
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - MAVEN_OPTS="-Dorg.slf4j.simpleLogger.log.org.apache.maven.cl‌​i.transfer.Slf4jMave‌​nTransferListener=wa‌​rn"
    - PODIUM_UAA_RUN_PORT=8999
    - BROWSERSTACK_USER=barteldklasens1
    - secure: HLkPx1Gmv3JT+Ils9KBPskAXNXHZDLqIvIvJcefTTye03g2eGg16bdLBrCrEtd+wWaKjQW3vH2oZLnZ/rlr8iEHn23ELG+EoFXu/df419mjGvw1aQzjiYCLniGzJ3TkB445RUDQc2TizMJVukPQfQTrsvshu8lM7SbJLCSG8zAC+DUHmzq6ytjwEGhKPUZQtMvGmYkdV07hC0LAckgYnqkuze6b9f07UKDRg8LtdZNQnBugmktJq4bU+S7DRKZB4tuHGox8uVCZ/ac94GK3sE4xpM4fGaoiq9MyQdMM0r6LLg1FJL9ED5Ny2P8qEnOnSaa25TkmVmLmLoyK3wZJY7i1n18dJTuU+9t7j2Dp84FYwDHGQvWuNyqhraglznD5+N3TMEpCMf/muctPBlXS9108S3Ph7te3SbM/mz69xvvgNI8fyjRS7YpkU7zONc1Zf1kAlOThEx4lEb7TuygZvmphIjnx1SDMIOEhag8HPCDGI1ywhhrm3Esb8NrSagXZeUaAl4mNnEvMjmT0MDGWzFyoRIGD3nZFkkyDR4oSQosncDmIfsO0rJTYzZXojGeq8nwuUDYDCQ9JV5zfcXH3AUIunGUEyMIHsWUeK8unftv5UpWMG++lqcrltfp3/yq1vwP00AnbhcoESvD4BJLNg7OlQBcfvVsvMcadoLjvCMws=
before_install:
  - nvm install $NODE_VERSION
  - node -v
  - yarn --version
  - java -version
  - export TZ=Europe/Amsterdam
  - date
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - chmod +x $PODIUM_SCRIPTS/*
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - mvn install -DskipTests -q
  - pushd podium-gateway
  - yarn install
  - yarn link
  - popd
script:
  - $PODIUM_SCRIPTS/01-docker-compose.sh
  #- $PODIUM_SCRIPTS/02-tests.sh
  - $PODIUM_SCRIPTS/03-run.sh
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
