version: '2'
services:
    podiumgateway-cassandra:
        container_name: podiumgateway-cassandra
        image: cassandra:3.9
        # volumes:
        #     - ~/volumes/podium/podiumGateway/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    podiumgateway-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: podiumgateway-cassandra-migration
        links:
            - podiumgateway-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace.cql
